version: '3'
services:
  typescript_build_tslib:
    build: typescript_build
    tty: true
    user: "${_USER}"
    privileged: true
    container_name: typescript_build_tslib
    volumes:
      - "../:/target_data:ro"
      - "../build/:/target_data/build:rw"
  sass_build_tslib:
    build: sass_build
    tty: true
    user: "${_USER}"
    privileged: true
    container_name: sass_build_tslib
    volumes:
      - "../:/target_data:ro"
      - "../build/:/target_data/build:rw"
  web_server_tslib:
    build: web_server
    tty: true
    user: "root"
    privileged: true
    container_name: web_server_tslib
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "../:/var/www/html/default:ro"
      - "./file/etc/tls/live/:/etc/tls/live/:ro"
