version: '3'
services:
  typescript_build_tslib:
    build: typescript_build
    tty: true
    user: "${_USER}"
    privileged: true
    container_name: typescript_build_tslib
    volumes:
      - "../:/target_data:ro"
      - "../build/:/target_data/build:rw"
  sass_build_tslib:
    build: sass_build
    tty: true
    user: "${_USER}"
    privileged: true
    container_name: sass_build_tslib
    volumes:
      - "../:/target_data:ro"
      - "../build/:/target_data/build:rw"
