version: '3.4'
services:
  typescript_build:
    build: typescript_build
    tty: true
    user: "${_USER}"
    privileged: true
    container_name: typescript_build_${_PRJ_NAME}
    volumes:
      - "../:/target_data:ro"
      - "../build/:/target_data/build:rw"
  sass_build:
    build: sass_build
    tty: true
    user: "${_USER}"
    privileged: true
    container_name: sass_build_${_PRJ_NAME}
    volumes:
      - "../:/target_data:ro"
      - "../build/:/target_data/build:rw"
